name: MICROSERVICE PROJECT COURSE EKS

on:
  workflow_dispatch:
    inputs:
      apply_or_destroy:
        type: choice
        description: Run terraform apply or destroy
        options:
          - apply 
          - destroy
        default: apply

env:
  TF_VERSION: "1.7.4"
  AWS_REGION: "us-east-1"

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Install Terraform manually
        run: |
          echo "Installing Terraform ${{ env.TF_VERSION }}..."
          wget -q https://releases.hashicorp.com/terraform/${{ env.TF_VERSION }}/terraform_${{ env.TF_VERSION }}_linux_amd64.zip
          unzip terraform_${{ env.TF_VERSION }}_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform version
          echo "Terraform installation completed"
          
      - name: Verify Terraform installation
        run: |
          which terraform
          terraform version
          terraform -help
        
      - name: Terraform Format Check
        working-directory: terraform
        run: terraform fmt -check
        continue-on-error: true
        
      - name: Terraform Init
        working-directory: terraform
        run: |
          echo "Current directory: $(pwd)"
          echo "Files in directory:"
          ls -la
          terraform init
        
      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate
        
      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -out=tfplan
        
      - name: Terraform Apply
        if: ${{ github.event.inputs.apply_or_destroy == 'apply' }}
        working-directory: terraform
        run: terraform apply -auto-approve tfplan
        
      - name: Terraform Destroy
        if: ${{ github.event.inputs.apply_or_destroy == 'destroy' }}
        working-directory: terraform
        run: terraform destroy -auto-approve